#!/usr/bin/env python

import sys

pattern_files = ["grok-patterns"]

def main(requested_patterns, dialect):
    patterns = {}
    for pattern_file in pattern_files:
        file = open(pattern_file)
        patterns = dict(patterns.items() + parse_patterns(file))
        file.close()

    invalid_requested_patterns = [p for p in requested_patterns
        if p not in patterns]
    if invalid_requested_patterns:
        for pattern in invalid_requested_patterns:
            sys.stderr.write("Pattern not found: %s\n" % pattern)
        sys.exit(1)

    flattened_requested_patterns = '|'.join(patterns[p] for p in
        requested_patterns)
    sys.stdout.write(flattened_requested_patterns)

def parse_args(args):
    options = {
        'dialect': None,
        'patterns': []
    }
    for arg in args:
        if arg in ('-h', '--help'):
            print_usage()
            sys.exit(0)
        if arg in ('--raw', '--ruby'):
            if options['dialect']:
                sys.stderr.write("Only one dialect may be specified.\n")
                sys.exit(1)
            options['dialect'] = arg[2:]
        else:
            options['patterns'] += [arg.upper()]
    sys.stdout.write("%s" % str(options))
    return options

def parse_patterns(file):
    return [separate_name_from_pattern(line.rstrip()) for line in file if not is_blank(line) or is_comment(line)]

    for line in file:
        line = line.rstrip()
        if is_blank(line) or is_comment(line):
            continue
        print separate_name_from_pattern(line)

def is_blank(line):
    return not line.rstrip()

def is_comment(line):
    return line and line.startswith("#")

def separate_name_from_pattern(line):
    return tuple(line.split(' ', 1))

if __name__ == "__main__":
    options = parse_args(sys.argv[1:])
    if not options['patterns']:
        sys.stderr.write("Must be called with a pattern name.\n")
        sys.exit(1)
    main(options['patterns'], options['dialect'])
